language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm test
deploy:
- provider: elasticbeanstalk
  access_key_id:
    secure: "dpi/G7ASEpWSDr98ImRrFUXay/3CHEa8168426IEq6LJHnWdkcTyIfsKH/M/MqgRCn4Z8zKy3eE75wplXG0FFA0ZDgPwMlDSehNAi8M0j9qz+g249S4/u6L+NpqsWOEnXmIz8PCFXtl+Vsu3obgDVhoOMmABaVtpSQ/vD2mVJTzBPL1ekRqfvb+dLlR3JXZGhTNgX3uzmb81zZ8l+cTjq1roYA2CJdQgawI8TIvJID+Xpm+GBDGqT9wxXGoGOUMA3k5VeYIUw526xPRN6ienios0xfJXOt/JFBEMDyO5sQGcF1sAJdbby3x+tS+ELoaBScimu4pLa0hKfleJG63JtJehClwIuEkeGkKDH4wZcOBALjFjgPRb7aLnoIZufdV4a1iWm+UAUMBBtxgyMgKFLYSgpfk/UsRuGqAmJx7m+AYmO7QA8fV1M4pir9GTeCaoUmJsJ1Lbl6mjFsKIx/9RhuCnVVXYhYBW+HT5QL3caJJbIfzGmI7Q6uuPhMz8hLkax7x0/33ge0eSD9y2J4Uv+8DbgzvCbqTHZdHuLFdLgHCK6CSv6rX52j4HjaxfB5st++7zPQh/rbVPCG15HAS6COaAZdlblY0EBIQAi426TxcnmKsU7HrDCLZgjVTNZU15iFpjZnsfUOKBtphzsTbuRt2ZxLuLZL3drDH3M+SRjPg="
  secret_access_key:
    secure: "DUaPrKnMlyDrZWR9sqy0zA5jDICYAZ3HazDz5O7OMUFdL+z9I4tlgb0QcoowAdRml+830vSV13Ycp0VqyT89kXH33Qj0hbW94aGutiX0N6CfcengpgMq3vAEbn+433JZAUmtDyoipGXRMFbZGJD74BWFKL7eV+o9D3U8vZ+GEzFttdNbFia5Oem6Cb9H2ASHXSgYczA8H9XKtam1onvy0Kfvv2F4m9VADdgoCxDdQnGaJLCk/NURzPWXZ5XaCRc3g597fKco4lnXauWZ6oYZJikU4TFpdpKrmsZA4Po4mOYuSkJoVu0oDaO8RitKBzrHOx5jOxt+n1IpWcgSPN1nGFY34ThCrvtwD28ZBj/6b1LbNUit/JiahlmZJGEXQbCnRFmQe00M+2SmzOhzV0N8k+ZpAiHo7rpmxbNqKpMjse9faFHsJ5cpQeqb1+AhjpbqeFihhTdfQAZorSAX8mA7RV78zxX8cYVePLWmyTKHBDyTt+lzzG1n494HoO/iyQz39mJU8unNAplKU3tadQ6iESOkTtLREjx9fMxmFexf44kWKzIKJt9hoGsCz5RNQLK9RIpx55jrfWmKmrm2gYJWMjdSJpxG8onfMd/KbcV9B8lSDvyWS7kFGCX7Fbux5MjhB24WECHmgtn1qi/0bPl/mRLDcbE5uE+676b1+4Efvgw="
  region: us-east-1
  app: Socket-Server
  env: socketServer-env
  bucket_name: elasticbeanstalk-us-east-1-031052761859
notifications:
  slack:
    secure: IsCJP58JKofvwy4jVC4DEZSUShLp+i4V94dzhKSoFrhRFKeT3Te/Hn+uDPBT+ZwTcs7QF0k1DfBHTZt0za1U/Q2fabhxxarrtR3v9DGWo2OfdBjyY9TM05JmZyFESov4CxzA4USvFd+GO7P6QY1IhdDF8oSa9dCViTAerBOGLMk=
