language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm test
deploy:
- provider: elasticbeanstalk
  access_key_id:
    secure: dpi/G7ASEpWSDr98ImRrFUXay/3CHEa8168426IEq6LJHnWdkcTyIfsKH/M/MqgRCn4Z8zKy3eE75wplXG0FFA0ZDgPwMlDSehNAi8M0j9qz+g249S4/u6L+NpqsWOEnXmIz8PCFXtl+Vsu3obgDVhoOMmABaVtpSQ/vD2mVJTzBPL1ekRqfvb+dLlR3JXZGhTNgX3uzmb81zZ8l+cTjq1roYA2CJdQgawI8TIvJID+Xpm+GBDGqT9wxXGoGOUMA3k5VeYIUw526xPRN6ienios0xfJXOt/JFBEMDyO5sQGcF1sAJdbby3x+tS+ELoaBScimu4pLa0hKfleJG63JtJehClwIuEkeGkKDH4wZcOBALjFjgPRb7aLnoIZufdV4a1iWm+UAUMBBtxgyMgKFLYSgpfk/UsRuGqAmJx7m+AYmO7QA8fV1M4pir9GTeCaoUmJsJ1Lbl6mjFsKIx/9RhuCnVVXYhYBW+HT5QL3caJJbIfzGmI7Q6uuPhMz8hLkax7x0/33ge0eSD9y2J4Uv+8DbgzvCbqTHZdHuLFdLgHCK6CSv6rX52j4HjaxfB5st++7zPQh/rbVPCG15HAS6COaAZdlblY0EBIQAi426TxcnmKsU7HrDCLZgjVTNZU15iFpjZnsfUOKBtphzsTbuRt2ZxLuLZL3drDH3M+SRjPg=
  secret_access_key:
    secure: RCU2CzX8Jtxo/iPgW+gI2KUtBCJiChV8h5wXH0Nk3+kG8+6+m+PCOUuRAaiSrEsRKcr+eHxPGTYnGgsV5rP2TIwdJFITjPEwx2+2FD0SR56OQPhheB0ISL5w8SFcDNlmnmTRhD9JsWxC/9FckofxovXLg9vvA5iC6cN25PTi6HGL9iihuNYlDb/cDKvKzfcNaw0MAPDvx0P+Tb4a1gWe3Rb8CVy0anXCCTaDC/zc68+sC9CmoSmEHPFY9wbCwJfGVICBeoYPGYxw4iXHwRsHAnalCYAv5wfK0YU6BpW1pI8j6zdaiSztEI6f7HwOlV7U5H5y1w5uxgmpZRf7JON+/JM0PJjXZVcPWsglDMGl62cCfOv+E8v6wfsWNdcUvHy6UL3YIkBYAWooB68i+MYMTzNLBZWjwYYUzXB3+h0KXoMrNw3j9oOlPNcJq5qnR2WjDzN8Rkk7nl6vQpS+TvfPll4uVzTNA5e7IoiBWxLwWd9VeXjg2ccmQt1l1zdOZI0gBJTjy0VjsWy8MEw4uhMPV6pHaXB+q2oO5L+VvJ2mVQNIqQ0WOe9LEetvOqsiUmyXxhwQvpOUuzen907dpMGd9Uya6AbS67MlOo5ePtG1q1wuda3z7FgaUWM+Bk7vZWuQB4TaX+eAwz5aXfJ+nnCRHkw/6VFZpFgV5oDM462irAY=
  region: us-east-1
  app: Socket-Server
  env: socketServer-env
  bucket_name: elasticbeanstalk-us-east-1-031052761859
notifications:
  slack:
    secure: IsCJP58JKofvwy4jVC4DEZSUShLp+i4V94dzhKSoFrhRFKeT3Te/Hn+uDPBT+ZwTcs7QF0k1DfBHTZt0za1U/Q2fabhxxarrtR3v9DGWo2OfdBjyY9TM05JmZyFESov4CxzA4USvFd+GO7P6QY1IhdDF8oSa9dCViTAerBOGLMk=
