language: node_js
node_js:
- '6'
env:
  global:
  - secure: G1RWlnwPIPSW2XRD7IItotgzTw41IAktyt2VurJwOp3xCIrmeHOtby6ox1x3Ph80Tzp3m3zLENof/sPsgOwRQgUOQ0nScpVGBGsUTAc26LL4SSs+7LGUAohm3EFTHPWU+78ZZMe3njK2fT86XP19FH1CupxgQ1vTpQI1iFChDD0=
  - secure: bnBfgN5eIAsCVdo+tMhjO88GRfUAEIkD0HFcOMEezP1YQv1bIFU71l5v4aT348RD2kuu6kihWApIqsEe0HjW8u0umPV6aLHuEuUrKGyxwk1x81bhP0KpgQgx+/Qbai4Q6gk+U4TWk713Ezu0j0GJH8jxixvyXgrJjfA/1yvHCdg=
install:
- npm install
script:
- npm test
deploy:
- provider: elasticbeanstalk
  access_key_id:
    secure: KUWS26l/RxjM7Fn5zy9fSVpF3kQzSmtkJQ7gGLwEqQ/QtrWnAWVyo6S1cnqNx57SChOTzxU15TcAncDQU3Ciy0m7rkVPQnXmfD9UVt4lZraMMDIk+oXh4i4l6yXFjei5LhxoHmtidinH+gl4R05Doh5ptli3sVHX1CaITjAKNSg=
  secret_access_key:
    secure: OcNlZr8vhlFKlSKEurZc1+NM/7exhr7JpOX4rJ6CqS1bly5Lh5UZ+GupZO7CM640nDrqwzQBKrkqDqPjwqEsbKIEU8NuDpfbG0/uRI4Ab/fhbPLzQPihLTjgkqI8ZlpSJ93K8fX2UC3SrVkyv29xzNZHlNp/q7GBaA95JRzelqQ=
  region: us-east-1
  app: Socket-Server
  env: socketServer-env
  bucket_name: elasticbeanstalk-us-east-1-031052761859
notifications:
  slack:
    secure: IsCJP58JKofvwy4jVC4DEZSUShLp+i4V94dzhKSoFrhRFKeT3Te/Hn+uDPBT+ZwTcs7QF0k1DfBHTZt0za1U/Q2fabhxxarrtR3v9DGWo2OfdBjyY9TM05JmZyFESov4CxzA4USvFd+GO7P6QY1IhdDF8oSa9dCViTAerBOGLMk=