language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm test
branches:
  only:
  - master
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: g6TYRkmIAitzoXo8Yfm3qVe5t2ys8KzIoMz6W4Y/1erdN7l5RB/d8vyVrA8xivOHjgQVlVSAHMnslW6fIg4bK+/bEhgp0kSvsD2xeDN1/IdrBnArcuxlZJy5Tr42bFWv/um84ShGcO/BntJLvSjE5qA2QzwcIL+Ss1KJuHQeBdeypaGhq4NRBKp8ig0Z43KAvQ61VyGy9s6KC1g+Hslr3a42TjWstSjTc5UfBTDTYbn9fkLk+8ySt5WxEUJI6rMT6cgQ0Fbntg1p0HrOkh8Xlgg/30WUe+6ajb+Ge8R0zmrWWEb4KY6QF2eHNtFDw2cvFlIt0DcpNekXVPrvjDvDPCv2XmHJ+ATltfWbSD7KfolfdgUEWPA/+ccf9xaB2FSTojHIEfwSihKn3QHlMgyp5cYZlsrsBJpnA0jg/OUKjSKBw0NiIGhfBUtQ/bTs8c60ifLrulFySHr6gqBqs72Ht9qsrzHrwMFpri73IfnZkNqFJxGOppzrcEl2/W3VJCsnAXo8gFf0ydSeeJwwFqoz6yCVXZkbG0GMrZiEGjrzS7x3dq7diWpAUrsUrd7D+bFmGBjE6wmeoOmY9/PSXq/fDN6QJzZ7EFOyv/Hx+FGPYFIDgkZKvOJ2RcEQnzyHx3l74kLRXOQ6yhE27dTNZLi/XLnWIdlOaqww3tfE82qDNXA=
  secret_access_key:
    secure: ZyC0ML42O1tJqJT/S2LRv9yCXBplfvV7Lww+CQwlQxAx0Z5dstenWmeVcDPqhgs12kywjkfAiLnAfKoqFe6GsraJFly7UOAFzUh5eJJRpFG+BcEhy3frYfRghTmDVPozoKNT7iVBE110h3L8oheNpsMc0XMf45uuKZ36QBwnz0vxw+JPAvmxBDrn9EEJGClzFtdkHKUxE2LcEvTKOHOqtrIS1Toh68ISVpOxjkf1g5OJDHXFC7iRPEDPJdjJhEFg0GsCqopYrdYHRZ3QcxBmGexbEh8D+0z79AP3mRMaXEYY6e/HWh5OqQilLrtTUyipBQ1kGXbSWgRNzUOtNvgq/1GJKvPua4IgV4IYQNe74XtfEYlxBe57jg/xYh7Pi9dwLibm+f4HDae51FMVkmwzObwWW+0ts7hEzVJaq6M4WwWQtRGaujVXnQoN5ZTs0qADr6XHO2+zntE/saWc7aG+81Ae0TTVtA2MgDwUisxRoLSzvONEEPhW8DQ+9GAOCqgekDQ2oLFLBaziOTVThgslQTAax9mWRY4jbUP7V38BkVGqtc1zUUZ53r5kT1hURLHyYN61q5akkflYX0rtZaIYoOAJEg2O3aOa7K4VjSstCrjZgtxd1SfJ8r2ytMinL9AL/j4uunNC/LXPcookLLHYHtyoXTwCIsTaAgwv6fXiQeQ=
  region: us-east-1
  bucket_name: elasticbeanstalk-us-east-1-362999620065
  app: Socket-Server
  env: socketServer-env
notifications:
  slack:
    secure: IsCJP58JKofvwy4jVC4DEZSUShLp+i4V94dzhKSoFrhRFKeT3Te/Hn+uDPBT+ZwTcs7QF0k1DfBHTZt0za1U/Q2fabhxxarrtR3v9DGWo2OfdBjyY9TM05JmZyFESov4CxzA4USvFd+GO7P6QY1IhdDF8oSa9dCViTAerBOGLMk=