language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm test
branches:
  only:
  - master
env:
  global:
  - secure: G1RWlnwPIPSW2XRD7IItotgzTw41IAktyt2VurJwOp3xCIrmeHOtby6ox1x3Ph80Tzp3m3zLENof/sPsgOwRQgUOQ0nScpVGBGsUTAc26LL4SSs+7LGUAohm3EFTHPWU+78ZZMe3njK2fT86XP19FH1CupxgQ1vTpQI1iFChDD0=
  - secure: bnBfgN5eIAsCVdo+tMhjO88GRfUAEIkD0HFcOMEezP1YQv1bIFU71l5v4aT348RD2kuu6kihWApIqsEe0HjW8u0umPV6aLHuEuUrKGyxwk1x81bhP0KpgQgx+/Qbai4Q6gk+U4TWk713Ezu0j0GJH8jxixvyXgrJjfA/1yvHCdg=
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: p7vTb3Lx10Bl5pSHjTCxJFR5TKKFkDmVA05vuDKHnXwmaiCg2hmpPoQh+JCzTbzMmydCSngIMXd/c49lBiUvySie0MFhShasKWiVFokcMCiboU9g/MouX9dUGu12clePMiQPe57G2g83gclSON1DFoCIkxr9N7XuphwaBGDSy1dTdOh8AqyqbNrhkfmE/z+SN282WFQ3eLm/MYMnKu5nJflN+e5s7z+vUzDWFr+PMp43ldup4H9mksTC8S7LXYDiIyUtJGepLUMekl/mh0VxIvSUp/u4yEQvE9VgFAm4aj9+DpA0/q5adBdR1nz7Hoi1ugC7I4igdXfgmtcWGqJgTJpptlLNXcU9S7aBg+9AKtgEzomp7xhQTW22dCmH4ihtm8CYaDyYkpSkOd5FXVq3Niee1rH03vC7umYMJBl+y5wrq/8feqRusCM/i0sUWreUonDppH1bASCFsC30BmVU9j3xxbQvI7VzqywDrofMfbxwKZVmu3P+wptei8ps2tYZqrNUXi7nl4JiAzl6cnpxklE971o+IrSebBktLITSIQBIL8GgS717Wgtsy5NUoUWlxW4nW3mHb0pA67bAe3NyROhgyq99sL4vwV3hz1O//KBVFlOE6VZC442DMXif7Qhh3P0zS7gxvM7GE+QWBkYWSnRhI9Wg9gDEdGpKc2JmnKE=
  secret_access_key:
    secure: qCzG/oNHqGDxHF1nie6R894PUTxEm3WnJH25tqxBSu5H3xPp03YCJa8jfrB0MnqNxrzZRlvyszwIq/vkiuNt+d3EqtfBAyDB24VoJ4iZeCzzw7IKcAZG4/QiFPQvN3eSyV1bOAcPIAxgyABNOqu1ZkjbhDMCE2UiT6hZZ7kbXFpiMKPkBWOLF5uPFPuYEO7cq8zZJtsYyanTOMaFsPXHc1xVzWzqZkYRy942+whweRhpQeFCBFaYKyjvTp+RqVztilQBVUIybUXwW+icE0DrhdR/3XrRWmMfEbR4ZgsAU7N+VgLbyyBKQHj3DNaejlO+C5EErjDYHHWTJtiy96023YTWfIABtinEZb58fHHAM8lUx0Md6AXTU7DzZqnnx8yxwxxn6bclTU8KnolRGxANnST80LiivIiJwu95lhxE1wPJ0fh+eLsjdypGMcc3nAE0ExtkZxVKA0n3wmvEgar+xtemVsKTzH8ELHzi4D5eah/94TYKWM3JI6ZAfyYIKcLd3WsThFXHBC2GRq8BgPLIhFVLIxTZjTIJ5Xw287RHNJTq5ZgCIZEqwiGjIbYYYMuTChi9iJK7a3EYGiOw1YiLHpGG0pAFyhYkUbIxqTtBwdnvMiClkFDT5Cko4tBfPUaG0Sg4vP7oC++GXKK+3Ksrbfz9YnTTOCdXkBrN87olO2E=
  region: us-east-1
  bucket_name: elasticbeanstalk-us-east-1-362999620065
  app: Socket-Server
  env: socketServer-env
notifications:
  slack:
    secure: IsCJP58JKofvwy4jVC4DEZSUShLp+i4V94dzhKSoFrhRFKeT3Te/Hn+uDPBT+ZwTcs7QF0k1DfBHTZt0za1U/Q2fabhxxarrtR3v9DGWo2OfdBjyY9TM05JmZyFESov4CxzA4USvFd+GO7P6QY1IhdDF8oSa9dCViTAerBOGLMk=
