language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm test
branches:
  only:
  - master
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: hEwwQm1/FzuL1eoQvbKBE/swC11dH/n0fouEBlyIUMEp+2aBiRsymI8C92ZOpcciErF50hkgtha2QaBgt9LZyY85BsGsE7zh8QQEw+p+Lf4HdGyRuBmb1RDNfY6ooIn5Wd5XNw4xjA0rdQoBTI8pOt+n0K+YrARpFUCqV0DerCYA+0/L1Np3UYc8VEmSLMF1iR2UVK9OYClLS5P4KJCZ/HOQvq0McbxRqITdlzyLe28KAQmMjAOZQyVJcMhDBrWz+xIiqNIZZQr+28oS/CzirBbdC7noGiINseAbxqZyCAuY1thL2AsrLnzaUnRNgvPKAvlK5Qoz5HJT6CbpB9aO9aa7QU2IL9gFcuzR1YbXlt+oju0ZL+vjGvR/CfxSPiQeXYveTP29Um1NUN+ZLigko7ZQNFc5I7dmJUSSgQmwLb7IsVmpi0NrS+R10a0687+VsTdnD0ayr7lNvKBo9ZjU9eOZ7BBPT1kZQXb1iteSq6BzP2XJg6qbrhG5Vxr+aZsnEGmuvdUi6UQqe86xQ8fvJyVEL0PxBxBPpDSyYLRo+Mz9qdVNPa7vXEIVZ4dPTE/JsKdEv+PlrqUVFFh9cktVYCwCS9Z2IfxE4dZVGEHLbKKWUh64G4P3IdzjEBNhQ59/2wC0xQ+dU4599nrnhLLxrqofSfxnsd7r1chzhH+VOdo=
  secret_access_key:
    secure: SEKfCuMyzlUUbPuRbMIpHkcExMh85gGMliS1iEYa6zKjvdTG/adC1FJsh0njvn8QWdY54SC3QlYRYLmigHantn9vxJetMkWOWs+QD0fXfG1agdS5Qh9EWOdK0+77wvoV9iCH21RV3TrE6wEGBBtkJzJM+Mq6XaUwjq7DIetVR2YFMT7+X/ZfS5GcA4zLtl2EbMAEPwJ9/TNLBNK3ZyQBINwxy01Amq5odUO7VVHPavBIN6uj1AY8TyBi0FnFTwvX463NgbEd9q1gTUrHNH/QgvE1bU3Q1y0mpbhJT7PGGD+DLi3e+Cpw76RMWGGr3qsWK8ro7LAFh0epC+KGH97LszEVch84uKKOzuJ7Lhv1KzC18P4MmkJxrOTRtfekxHIA41Qz0QZhrOCIQO5M48htpjaplegFqDFTDYuEJPCVFLtGRZq20U7+TriVxQ8eWbCTYRUWg1ww83S1gv+CPmti4Ev4lncQTVcgOe5VgT/zC/ZP42UWJPXX39knLqzEXMcUHrqJraW/Do/vUhtRqfbNNBcf4TcKMNUDXYuwQAMqQt6MMLUf0Ty/sgbYC9L2G1J6K+AuB+EOzPWYXGcjRUQfXMCWMZMLNo0DgTJeCWmY2zVOWRNKk1RmgjRlYAzkUHfyXQlfdtPAFfi31DgJwcksxusrgyqeYuS4nlmIVbEHMqs=
  region: us-east-1
  bucket_name: elasticbeanstalk-us-east-1-362999620065
  app: Socket-Server
  env: socketServer-env
notifications:
  slack:
    secure: IsCJP58JKofvwy4jVC4DEZSUShLp+i4V94dzhKSoFrhRFKeT3Te/Hn+uDPBT+ZwTcs7QF0k1DfBHTZt0za1U/Q2fabhxxarrtR3v9DGWo2OfdBjyY9TM05JmZyFESov4CxzA4USvFd+GO7P6QY1IhdDF8oSa9dCViTAerBOGLMk=
