language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm test
branches:
  only:
  - master
deploy:
  - provider: elasticbeanstalk
    access_key_id:
      secure: XIxPDezOPK2PJHtujfJPi7E8lGo0Otw1OCn/0koan0UrMp29H12pVF/ZV4dJbxLF8kPy7anvbchuUTWgKrU6b2l54CNhuLni7rvRTo68RImNeEczn3SRvyTaPXaG+5etw1eQ/8p7AawuSCan1cChcls3r0kPz4O7vULkB6Gr8V1J69xdgQ7Xep1dGPQNLrD4ryZg+QKH0W27WRXCYb2Dzt59moo61G2/dF+gaimNGxURwEa33ukwkLkHxyGGp5/jQOtpvBrLR9cXnyMpKU+o6+DQJTIhtSwXbmwZxVtBQc/k9y3Ago6ZM7IGYd+YWFGPQqDgnhxFeswzfRt7sTrAzmFY4zHk6kg6NyHUkd1Li8b/HSNZMXGtVCMOFBl+gSesNMTfej2fiS+qrtttzqpl/ox2sTiBBRQqri3k6tMivTQ2g4Sv36Esg+rQQGcby49nHoWe6CJgUUsyxRtZ/byu0B8JcNdLiWorgLdH0P1tnUgkX3dZL/fN61ZoAcMRHb/hcSTBzzXVMGLgkWwMRJh0hU/KN3QNKwGeLeZ5B7hnW23eyNM9KPr6Bt6DOOXbPJ8vU41WrHqn/xsvafvvAxEiziGkgguwEIVcH/IQpEX+bFXL+pp2Z0usiMM6+IySJsBwEG+0EiRZcBklSZphAy7L8glu4bJarNR22ugBFl92OZ8=
    secret_access_key:
      secure: I8usvD6xTI0zZOYjMI7WjRRtBEBXR+7ir2uGhGgnP72iCAkKJdgEQ58ziOo1EhNPkZu960kOljnZ0ehfrqFBELr3wURInta1hbdxLJsUXCNTFs14QcIBylH2Kj+PsfUoRu5sxWOmNZqVLqF4nBAKEYoI/IATj0zDaHbcHOK+dvCAWhvXnsAKTVGdE+ogSadHv0UwZKlV3Fqdqjbg0QwMFXYcKBl5KqKW763XxQ0VpvvRmTmaXYd4P1kDjK0kapl6dd1QtGZuwHjqaKh7MXr8vbzbtJKZcMcWWBmXo7BWLBybWFRERxO/unclCgGaPcrjvy3LxH3tPQxANVl1hOnxI0xdrKP6XTD2Kb4R6lOScEUEBdJKCswnfYmuPTn1su8o87Z6h7qJz4bm3Yu1TLvLEnr/Bf0MjkpVGoYSrWtKu9pxTJcrBS6x53dRC5U+zLT/RkPuenASi51rm2ncSv8IIK8Dw46ajZ1+7kIwRuAWA9k2x/GDLVjUgK+haHgPcvnYsfXGluW0aEuGONdAb/fSCC9ChHr4tA57q5QAZa7KvxYlpCNVwQ9IVLd0xGg6xtrraLRbliPNd5UQUD9NFDOHnwqZGwXyRWqjFTEO4ojsHecle8BAf6+c9mDAZF3OWC5lESy5ZWH+Iv20++51lcYky4sdKO/2gt3NOUhtBlgW6eM=
    region: us-east-1
    app: Socket-Server
    env: socketServer-env
    bucket_name: elasticbeanstalk-us-east-1-031052761859
notifications:
  slack:
    secure: IsCJP58JKofvwy4jVC4DEZSUShLp+i4V94dzhKSoFrhRFKeT3Te/Hn+uDPBT+ZwTcs7QF0k1DfBHTZt0za1U/Q2fabhxxarrtR3v9DGWo2OfdBjyY9TM05JmZyFESov4CxzA4USvFd+GO7P6QY1IhdDF8oSa9dCViTAerBOGLMk=
